######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 23 13:21:33 2019
######################################################################

TEMPLATE = app
TARGET = systray
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
RESOURCES += systray.qrc

QT += widgets
